### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './mentions'

### ISSUE THREAD

**Issue by Maxcension** [defacto133/twitter-wordcloud-bot#5]
`C:\Users\maxim\Desktop\twitter-wordcloud-bot-master>main.py
Traceback (most recent call last):
  File "C:\Users\maxim\Desktop\twitter-wordcloud-bot-master\main.py", line 379, in <module>
    t.run()
  File "C:\Users\maxim\Desktop\twitter-wordcloud-bot-master\main.py", line 317, in run
    self.handle_mentions()
  File "C:\Users\maxim\Desktop\twitter-wordcloud-bot-master\main.py", line 131, in handle_mentions
    mentions = self.load_mentions()
  File "C:\Users\maxim\Desktop\twitter-wordcloud-bot-master\main.py", line 104, in load_mentions
    with open('./mentions', 'rb') as f:
PermissionError: [Errno 13] Permission denied: './mentions'`

**Comment by azcoigreach** [comment]
Same...  I am getting this error too...

**Comment by Maxcension** [comment]
Thanks a lot.
