### ISSUE TITLE
[Errno 2] No such file or directory: './output\\1514132223Maxcension.png'

### ISSUE THREAD

**Issue by Maxcension** [defacto133/twitter-wordcloud-bot#7]
Traceback (most recent call last):
  File "D:\Users\Maxime\Desktop\twitter-wordcloud-bot-master\main.py", line 380, in <module>
    t.run()
  File "D:\Users\Maxime\Desktop\twitter-wordcloud-bot-master\main.py", line 318, in run
    self.handle_mentions()
  File "D:\Users\Maxime\Desktop\twitter-wordcloud-bot-master\main.py", line 187, in handle_mentions
    img_file = self.make_wordcloud(user_name)
  File "D:\Users\Maxime\Desktop\twitter-wordcloud-bot-master\main.py", line 70, in make_wordcloud
    wordcloud.to_file(img_file)
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 642, in to_file
    img.save(filename)
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\Image.py", line 1925, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './output\\1514132223Maxcension.png'

**Comment by Maxcension** [comment]
Resolved by creating a folder "output".

**Comment by azcoigreach** [comment]
`if os.path.exists(self.OUTPUT_DIR) is False:
            os.mkdir(self.OUTPUT_DIR)`

added to line 47 of the __init__ function will fix this...  

I have also started a Dockerized fork of this project...  [https://github.com/azcoigreach/twitter-wordcloud-bot.git](url)
